apiVersion: v1
data:
    password: ENC[AES256_GCM,data:G+9E3BfrTnU=,iv:EC8FWYyD6pgKW26gUPwBVGgPNpV+wgsBc2xHDqMOYS4=,tag:A3P9wewQgnQMduieyRtdjg==,type:str]
    user: ENC[AES256_GCM,data:c+IJYr7lMTQ=,iv:gJckGvrFcJSdiKoua1fkCIaKkobR8mWikd6Y05+euek=,tag:FpUi+8h7t+ug49YlpTl99A==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWVYydTVwVVlsZTBoL1B3
            SUJ2bEVVMUFtaXB3aHE5ZmhnR1N1S2h3SG5BCjVjbEhMcmdJbnNPem5yRzVnSi9t
            QjZWMy9RRGZsclJvNjFIK1FsYUJ1TjQKLS0tIHJNcWNXSmc4dnV5VENXaW1EWXhJ
            TUxjZlgxSW5NMEZEMFhYalNwZ2FweTAK1QoIlmF6WfQHnY9Q7czH7Zw4vH3pCmNO
            J824HGBKyOCvDfhGx8T++GLHECKnt9wbqIrtMMfhzWQsSoSAEIXrxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qxgeq7aks6qmdwjpy5q23p85n62q89lp6ekgvkfp62ajsjkzdeyqsgk3l0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T10:52:02Z"
    mac: ENC[AES256_GCM,data:/a3WHiUi8h4pq60ZXBnAdbvJnCmjbDxAqzVbHJbS2O7gMn6rb/TaCYSh7Hr1A9cwV6NaHTgFnjReb+OXGV/cK64607jWvpK9ROp3Lr7l/FjFh2UBdvnhaR0g0NZY48tc/cJdIIO0Qpdzjm9EKebz+5k2k7ekv0u/MmHMwaZf5k0=,iv:rIVkdUWmfIkKjxgD697dRKsY69mhcfmNY+HmnEw7Q5w=,tag:7ngrO2sSdjErSrdA/JlPpQ==,type:str]
    version: 3.13.3
