apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:35FPxgFFvb/muM+tmlGTrwv0wM+FmLrQkdc7AZa/bkJaSArAyTj1fxLRHRIFWvF9KNgCxJRShvvGCY/BKTryc509Ui2tAMhzsxkV4r0C554ZlXq4FU2NIZrymmYnf3pGw1q0KozFXmVBb9yAKIlkrW1BEEVxN45cIdUgECP1xE5CUJPJJKYCreH3H2X3LVkcwjtvx3pKTadwpaC2lg59R7YYluzo1Zq1Hf+LCe4O5EdzSUSCzXjVrnKVBkBUSC5gts3qIi7xUVCFVVEhvQ8S4NXR8DSBins2rAHs47+EBFN+LiF/SGcM3eV2v7w=,iv:ikOBp6DirLfFnbscBwnz/0nwSLrk8s9F3ahW+SqxEf0=,tag:n9kwGp0WE2p8KVQzNUm9Jg==,type:str]
kind: Secret
metadata:
    name: tunnel-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeFlSYVZXT0hqNWNVMW1P
            SUdtWmtRcjJPZ2VsMmJYYXJ3UlcyYzNVSkVvCmpNUkhFODdaQ0c4Z0NOTXJqQ3Fx
            cStBbVJEWEw4U0hPTGtURFZwUnhaR0UKLS0tIHZXWFJXWFdHQjd4WXJFbklMQmxt
            UmxZZFpZZXZibjFjSTNpU2JZMExLQmMK7NMws4IIfJjLi1Ay7POVsSC69hoVzmiy
            E6PBCf/s9Gyv7Y+im4CZ8MVYy7K4Ix9MzcIDBoxSxIb4lyFDEryMEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qxgeq7aks6qmdwjpy5q23p85n62q89lp6ekgvkfp62ajsjkzdeyqsgk3l0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T12:59:20Z"
    mac: ENC[AES256_GCM,data:aHvew1fyv97f6W7AbYP0dMspfyMowHFyd/4RTURoEQ+N9dkSofDZQmNmz8IfROxLvXjq8WvQfWI2jHPw38UePZdpLCYxsbb58I8CT08xTcUdy+90mKnJDHjUEWI9OxA+nzGXu+lwZUsPClVzgJXLlTUgVeQgADWmloAs4Qtc+rs=,iv:WLAAo69f1vccuQUZYBwHbUAc/a+mRgNlXgIXHNsB6e0=,tag:T0wETzFD+f5iVgW8trxSOw==,type:str]
    version: 3.13.3
